# Generated by Django 2.1.7 on 2019-03-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_room_id',
            field=models.IntegerField(default=1),
        ),
    ]
