# Generated by Django 2.1.7 on 2019-03-23 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mud.Item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mud.Player')),
            ],
        ),
    ]
