# Generated by Django 2.1.7 on 2019-03-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0006_auto_20190325_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='img_extension',
            field=models.CharField(default='png', max_length=8),
        ),
    ]
