# Generated by Django 2.1.7 on 2019-03-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0007_monster_img_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='max_hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='max_hp',
            field=models.IntegerField(default=100),
        ),
    ]
