# Generated by Django 2.1.7 on 2019-03-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0008_auto_20190325_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='player',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='player',
            name='defense',
        ),
    ]
