# Generated by Django 2.1.7 on 2019-03-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0009_auto_20190326_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_hp', models.IntegerField(default=100)),
                ('monster_hp', models.IntegerField(default=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='monster',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hp',
        ),
        migrations.AddField(
            model_name='battle',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mud.Monster'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mud.Player'),
        ),
    ]
